services:
  - type: web
    name: flood-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    branch: main
    plan: free
    autoDeploy: true
